version: "3.7"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: jupyter-nb
    ports:
      - 8888:8888
    volumes:
      - "./:/home/jovyan/work"
    environment:
      JUPYTER_TOKEN: '123456789'
      JUPYTER_ENABLE_LAB: 'yes'

volumes:
  jupyter:
