version: "3.7"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter-nb
    ports:
      - 8888:8888
    volumes:
      - "./:/home/jovyan/work"
    environment:
      GRANT_SUDO: 'yes'
      JUPYTER_ENABLE_LAB: 'yes'
      JUPYTER_TOKEN: '123456'
